In [ ]:
#___________________EXERCISE 08_____________________

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type(a))

In [ ]:
print(a.shape)
print(a[0], a[1], a[2])


In [6]:
a[0] = 5
print(a)
b=np.array([[1,2,3,],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

[[5. 5.]
 [0. 0.]]
(2, 3)
1 2 4


In [2]:
import numpy as np
a = np.zeros((2,2))
print (a)
b = np.ones((1,2))
print (b)
c = np.full((2,2),7)
print (c)
d = np.eye(2)
print (d)
e = np.random.random((2,2))
print (e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.16432965 0.80648615]
 [0.23738903 0.33110956]]
