In [ ]:
#_____________Exercise 07_____________

In [1]:
import array
arr = array.array("l",[2,4,6,8,10,12])
print("New created array: ", end="")
for l in range (0,5) :
  print(arr[l], end=" ")
  print("\r")

New created array: 2 
4 
6 
8 
10 


In [ ]:
# example 1

In [2]:
import pandas as pd
dict = {'name':["Smith","Karan","Abhaydeep","Copyright"],'age':["12","22","21","92"]}
info = pd.DataFrame(dict, index = [ True, True, False , True])
print(info)

            name age
True       Smith  12
True       Karan  22
False  Abhaydeep  21
True   Copyright  92


In [3]:
import numpy as np
arr = np.array(16)
print("The Original array is:\n",arr)
#shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray:\n",arr)
#shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(8,2)
print("\nreshaped array:\n",arr)

The Original array is:
 16

reshapedarray:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
